### ISSUE TITLE
Implement SIMD Galloping

### ISSUE THREAD

**Issue by lemire** [tetzank/SIMDSetOperations#1]
Would be interesting to add SIMD galloping...
- Daniel Lemire, Nathan Kurz, Leonid Boytsov, SIMD Compression and the Intersection of Sorted Integers, Software: Practice and Experience 46 (6), 2016.  https://arxiv.org/abs/1401.6399

SSE\* implementation...

https://github.com/lemire/SIMDCompressionAndIntersection/blob/master/src/intersection.cpp#L459

**Comment by tetzank** [comment]
Yes, i actually read the paper last year when initially looking around for ideas but i never really came around to make a good implementation of your approach. The very trivial testcase i have at the moment to measure the different implementations might also favor the other shuffling approach: both lists are always the same, very big size. I'm currently looking into adding google's microbenchmarking tool to add more testcases easily.

So yes, it's on my todo list. And i'll also have a look at your code to better understand your optimizations.

**Comment by lemire** [comment]
> both lists are always the same, very big size.

Right. This may, or may not be, the right model for some applications.

**Comment by eladmarg** [comment]
I've benchmark your AVX2 implementation, 
in some cases, the galloping on AVX is even faster than AVX2.
so this would be very interesting to see the improvement.

**Comment by lemire** [comment]
@tetzank 

I have posted some AVX2 code https://github.com/lemire/SIMDCompressionAndIntersection/blob/master/src/intersection.cpp#L701-L1087

**Comment by tetzank** [comment]
I still haven't found the time to really look at it. I just copied your galloping implementation as the interface is the same and run it with the trivial testcase on a Xeon E5-2660 v3 system.

| shuffling | time |
| --- | --- |
| SSE | 11624.23 |
| SSE asm | 9770.15 |
| AVX | 11003.53 |
| AVX2 | 7240.46 |
| AVX2 asm | 5966.18 |

| v1 | time |
| --- | --- |
| SSE | 14475.09 |
| AVX2 | 11741.45 |

(v3 and SIMDgalloping is way slower as the lists are equal in size)

As said before this trivial test is probably the best case for the shuffling approach and the worst case for galloping. In a different paper [1] they only use galloping if the size difference is more than 32:1, shuffling otherwise (and bitsets for dense sets). I still have to enhance the microbenchmark tests to make them more usable or add other tests in a different way.

[1] https://arxiv.org/abs/1503.02368v6

**Comment by lemire** [comment]
You can probably close this issue now.

All our intersection algorithms (including V1) assume that there is a non-trivial cardinality difference between the arrays, and this proved true in the realistic data we used. So this explains the results you are seeing.

> different paper [1] they only use galloping if the size difference is more than 32:1, shuffling otherwise (and bitsets for dense sets).

Absolutely, galloping is going to be ineffectual on same-length arrays.

**Comment by eladmarg** [comment]
In my case, (real data), the galloping performs slightly better.

**Comment by tetzank** [comment]
That's why i want to add more tests to see where which approach is better.
